reverse_proxy:
  - domain_name: hl.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 3101
  - domain_name: dav.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8809
  - domain_name: cctv.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8765
  - domain_name: ffplayout.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8787
  - domain_name: homeassistant.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8123
  - domain_name: cups.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 631
  - domain_name: pihole.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8081
  - domain_name: getaldea.axau.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 12321
  - domain_name: translator.axau.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 12320
  - domain_name: aula.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 13000
  - domain_name: nextcloud.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8082
  - domain_name: paperless.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 2226
  - domain_name: axel.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 8811
  - domain_name: grocy.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 9283
  - domain_name: nodered.ei.tech.eus
    scheme: http
    host: 100.75.123.40 # Margaret Tailscale
    port: 1887

  - domain_name: ba.tech.eus
    scheme: http
    host: 100.75.123.40 # Work01 Tailscale
    port: 14000
  - domain_name: bb.tech.eus
    scheme: http
    host: 100.75.123.40 # Work01 Tailscale
    port: 14001
  - domain_name: docs.tech.eus
    scheme: http
    host: 100.115.231.1 # Huevo23 Tailscale
    port: 82

  - domain_name: nginxproxymanager.ei.tech.eus
    scheme: http
    host: 127.0.0.1 # Localhost (Nginx Proxy Manager)
    port: 81

  - domain_name: exercisediary.k.tech.eus
    scheme: http
    host: 100.69.59.86 # Swarm
    port: 8851
  - domain_name: timetagger.k.tech.eus
    scheme: http
    host: 100.69.59.86 # Swarm
    port: 8989
  - domain_name: mealie.k.tech.eus
    scheme: http
    host: 100.69.59.86 # Swarm
    port: 9925
  - domain_name: influxdb.k.tech.eus
    scheme: http
    host: 100.69.59.86 # Swarm
    port: 8087
  - domain_name: mqtt.k.tech.eus
    scheme: http
    host: 100.69.59.86 # Swarm
    port: 1883
  - domain_name: grafana.k.tech.eus
    scheme: http
    host: 100.69.59.86 # Swarm
    port: 3000
