name: Update Docker Config

on:
  push:
    branches: ["main"]
    paths:
      - 'docker/**'
  workflow_dispatch:

jobs:
  dry_run:
    name: Test Docker compose
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload new Config Files
        uses: appleboy/scp-action@master
        with:
          username: naiel
          host: margaret2.ip.tech.eus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './docker'
          target: '~/naiel-docker-dry-run'
          overwrite: true
          strip_components: 3
      - name: Test docker compose and pull @ Margaret
        uses: fifsky/ssh-action@master
        with:
          user: naiel
          host: margaret2.ip.tech.eus # Reserved IP Address (to my local device) (example 192.168.0.1)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ~/naiel-docker-dry-run
            ls
            docker compose config --quiet && docker compose --dry-run up --remove-orphans -d && docker compose build
  deploy:
    name: Deploy docker config
    needs:
      - dry_run
    runs-on: "self-hosted"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload new Config Files
        uses: appleboy/scp-action@master
        with:
          username: naiel
          host: margaret2.ip.tech.eus
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: './docker'
          target: '~/naiel-docker/'
          overwrite: true
          strip_components: 3
      - name: Restart Docker Containers @ Margaret
        uses: fifsky/ssh-action@master
        with:
          user: naiel
          host: margaret2.ip.tech.eus # Reserved IP Address (to my local device) (example 192.168.0.1)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd ~/naiel-docker
            ls
            docker compose up --remove-orphans -d
